name: TouchFS
options:
  bundleIdPrefix: com.bluzuli
  deploymentTarget:
    macOS: "13.0"
targets:
  TouchFS:
    type: application
    platform: macOS
    sources:
      - TouchFS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bluzuli.touchfs
        PRODUCT_NAME: TouchFS
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: X44L3QQYVR
        ENABLE_HARDENED_RUNTIME: NO
